manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/mralex07
  projects:
    - name: zmk_tr
      remote: zmkfirmware
      revision: pmw3610-aml-nrfmicro
      import: app/west.yml
  self:
    path: config
